### ISSUE TITLE
How To Install ???

### ISSUE THREAD

**Issue by maddox222** [IsaacMeirelles/BeautySmart#1]
Hello 
I downloaded Your Project But I really Dont Know How To Install It and Run It so Can anyone pls help Us

**Comment by IsaacMeirelles** [comment]
Hi Maddox,

This project is in early development state, without usability ... i'm beginning on laravel programming and I intend to provides it as open source when completed.
I am finishing the definition of the data structure to start the data entry forms.
Any help will be very welcome!

**Comment by kamidehlvi** [comment]
Hi, I have installed XAMPP and deployed BeautySmart master file now its root content only appears.  Please help me to deploy it more over any other dependencies like laravel MVC Framework how can I install it on XAMPP. Also, need help to study database ... identify that database files or backup to restore I am using MySQL as a database.
Regards,
Kamran

**Comment by CARIBAL** [comment]
> Hola, instalé XAMPP y desplegué el archivo maestro BeautySmart ahora solo aparece su contenido raíz. Ayúdame a implementarlo más sobre cualquier otra dependencia como laravel MVC Framework, ¿cómo puedo instalarlo en XAMPP? Además, necesito ayuda para estudiar la base de datos ... identificar los archivos de la base de datos o la copia de seguridad para restaurar Estoy usando MySQL como base de datos.
> Saludos,
> Kamran

HELLO Mr.KARMAN! DO YOU GET D.B. FILE? SINCERELY!
